apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Sidhin-kp/gitops-2'
    targetRevision: HEAD
    path: app                # Folder in your repo containing manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default       # Deploy to the 'default' namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
